Shell : main.c call_echo.c call_cd.c call_history.c call_ls.c call_nightswatch.c call_pinfo.c call_pwd.c check.c printDir.c takeInput.c
	gcc -o Shell main.c call_echo.c call_cd.c call_history.c call_ls.c call_nightswatch.c call_pinfo.c call_pwd.c check.c printDir.c takeInput.c -lreadline -lncurses -I.
